require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable


# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 文字列リテラルをimmutableにするマジックコメントfrozen_string_literal: trueは使用しない
Style/FrozenStringLiteralComment:
  Enabled: false

# １行の空のメソッド定義を許可する（自動生成直後のファイルがoffenseとなってしまうため）
Style/EmptyMethod:
  Enabled: false

# その他自動生成で発生する規約違反は無視するが、必要に応じて調整する

Style/InverseMethods:
  Exclude:
    - 'bin/yarn'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'bin/yarn'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

# コントローラ
# privateメソッド可読性向上のため許可
Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/tweets_controller.rb'

Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/application_controller.rb'    
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/tweets_controller.rb'    

# ユーザーパスワードとパスワード確認のバリデーションをスキップする必要があるため、update_attributeの使用を許可
Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'

# 可読性を重視し、複数行の三項演算子を許可
Style/MultilineTernaryOperator:
  Exclude:
    - 'app/models/user.rb'

# Session関連
# 可読性・汎用性を重視し許可
Style/SafeNavigation:
  Exclude:
    - 'app/controllers/sessions_controller.rb'    
    - 'app/helpers/sessions_helper.rb'
    
Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/sessions_helper.rb'

# Abc Size:20のsessions_controller.rbを例外として許可（デフォルトAbc Size:15）
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/sessions_controller.rb'