version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2-browsers
        environment:
          APP_BUNDLER_VERSION: 2.1.4
    working_directory: ~/gadget-app
    steps:
      - checkout:
          path: ~/gadget-app
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.0.2-browsers
      - image: circleci/mysql:8.0
        environment:
          # MYSQL_ROOT_PASSWORD: <%= ENV['DATABASE_DEV_PASSWORD'] %>
          MYSQL_DATABASE: gadget_app_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/gadget-app
    steps:
      # - run:
          # name: Setup Environment Variables
          # command: echo "export ROOT_PASSWORD='${CI_MYSQL_ROOT_PASSWORD}'" >> $BASH_ENV
      # - browser-tools/install-chrome
      # - browser-tools/install-chromedriver    
      - checkout:
          path: ~/gadget-app
      - ruby/install-deps
      - run:
          name: Environment Variables
          command: |
            touch .env
            echo DATABASE_DEV_PASSWORD=$DATABASE_DEV_PASSWORD > .env
            echo MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD > .env      
      - run:
          name: check password
          command: echo "${CI_MYSQL_ROOT_PASSWORD}"      
      - run:
          name: check password
          command: echo "${CI_MYSQL_ROOT_PASSWORD_CONTEXT}"
      - run:
          name: check password
          command: echo $BASH_ENV      
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: run webpack
          command: bundle exec bin/webpack
      - run:
          name: run rubocop
          command: bundle exec rubocop
      - run:
          name: run rspec
          command: bundle exec rspec spec/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          context:
            - my-context
          requires:
            - build