version: '3'
services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/gadget-app
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data: