version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "deploy/back-task-definition.json"
        LoadBalancerInfo:
          ContainerName: "ga-prod-fargate-back"
          ContainerPort: 80
